### PR TITLE
fix #42 Updating rollup

### LINKED ISSUE #42: Unable to install with Svelte 4
Hi, after migrating to Svelte 4 following the guide at https://svelte.dev/docs/v4-migration-guide, I can't install this package. I tried to debug the problem but I don't have any clue yet except the obvious that it's something related to Svelte dropping commonjs support.

> Error [ERR_REQUIRE_ESM]: require() of ES Module ../node_modules/svelte/src/runtime/ssr.js from .../node_modules/svimg/dist/index.js not supported.
> Instead change the require of ssr.js in .../node_modules/svimg/dist/index.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (../node_modules/svimg/dist/index.js:15:14)
>     at async Promise.all (index 0)
>     at async load_config (file:///.../node_modules/@sveltejs/kit/src/core/

### PR DESCRIPTION
**Pull request by manuganji**
Seems to fix #42 in my testing.

### CODE REVIEW

**Comment by doppiaesse** [comment]
In my case the upgrade doesn't fix the error.

**Comment by manuganji** [comment]
> In my case the upgrade doesn't fix the error.

Can you please share the steps that you used to try this fix? Have you built it locally and used it as a dependency?

**Comment by TimonStadelmann** [comment]
Please Merge this. God dam Im waiting weeks for that

**Comment by xiphux** [comment]
@manuganji Unfortunately I don't think I can merge this as-is - you've updated package.lock, but your commit also includes a newly created package-lock.json file. This package uses `pnpm` and not `npm` as its package manager, so instead of creating a new package-lock.json, we'll want to update pnpm-lock.yaml. (by doing a `pnpm install` instead of an `npm install`)

I'm also not 100% sure this makes this project fully Svelte 4 compatible - I have no problem updating rollup-plugin-svelte and if it works for you, great. But there might be other adjustments required to the build, especially if they're going full ESM only.

**Comment by xiphux** [comment]
@TimonStadelmann Like many other open source maintainers, I am one person maintaining this project in my free time without any compensation. I have a life and have had complicated life circumstances for the past couple months. Please contribute respectfully and/or meaningfully in the future rather than just cursing at people.

**Comment by TimonStadelmann** [comment]
> @TimonStadelmann Like many other open source maintainers, I am one person maintaining this project in my free time without any compensation. I have a life and have had complicated life circumstances for the past couple months. Please contribute respectfully and/or meaningfully in the future rather than just cursing at people.

 I apologize. My message was very unprofessional. I thought, since @laugepetersen has approved this PR, that the click onto "merge" was just missing/forgotten.

**Comment by manuganji** [comment]
Sorry for not noticing `pnpm`. I'll change the pull request tomorrow. I can't confirm if this is all that's needed to support ESM only.

**Pull request merged**
